name: Deploy to Azure Kubernetes Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY_NAME: risinglionacr
  CLUSTER_NAME: games-multi-tenancy
  CLUSTER_RESOURCE_GROUP: 3DKittyPongAKS
  NAMESPACE: default  # Changed to default namespace for production
  APP_NAME: rising-lion-game

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set deployment variables
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "NAMESPACE=pr-${{ github.event.number }}" >> $GITHUB_ENV
          echo "APP_NAME=rising-lion-game-pr-${{ github.event.number }}" >> $GITHUB_ENV
          echo "DEPLOYMENT_TYPE=staging" >> $GITHUB_ENV
          echo "IMAGE_TAG=pr-${{ github.event.number }}-${{ github.sha }}" >> $GITHUB_ENV
        else
          echo "NAMESPACE=default" >> $GITHUB_ENV  # Use default namespace for production
          echo "APP_NAME=rising-lion-game" >> $GITHUB_ENV
          echo "DEPLOYMENT_TYPE=production" >> $GITHUB_ENV
          echo "IMAGE_TAG=latest-${{ github.sha }}" >> $GITHUB_ENV
        fi
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Build and push Docker image
      run: |
        # Login to Azure Container Registry
        az acr login --name $REGISTRY_NAME
        
        # Build and tag the image
        docker build -t $REGISTRY_NAME.azurecr.io/$APP_NAME:$IMAGE_TAG .
        
        # Push the image
        docker push $REGISTRY_NAME.azurecr.io/$APP_NAME:$IMAGE_TAG
        
        echo "✅ Image built and pushed: $REGISTRY_NAME.azurecr.io/$APP_NAME:$IMAGE_TAG"
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    
    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group $CLUSTER_RESOURCE_GROUP --name $CLUSTER_NAME
    
    - name: Create namespace if it doesn't exist
      run: |
        kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
    
    - name: Deploy to Kubernetes
      run: |
        echo "Deploying to Kubernetes..."
        echo "Namespace: $NAMESPACE"
        echo "App Name: $APP_NAME"
        echo "Image Tag: $IMAGE_TAG"
        
        # Replace placeholders in Kubernetes manifests and apply
        envsubst < k8s/deployment.yaml | kubectl apply -n $NAMESPACE -f -
        envsubst < k8s/service.yaml | kubectl apply -n $NAMESPACE -f -
        envsubst < k8s/configmap.yaml | kubectl apply -n $NAMESPACE -f -
        
        # Apply ingress with environment-specific configuration
        if [ "$DEPLOYMENT_TYPE" == "staging" ]; then
          export INGRESS_PATH="/pr-${{ github.event.number }}"
          export INGRESS_HOST="games.risinglion.dev"
        else
          export INGRESS_PATH="/"
          export INGRESS_HOST="risinglion.schwartzman.org"
        fi
        
        envsubst < k8s/ingress.yaml | kubectl apply -n $NAMESPACE -f -

        # Deploy production-specific ingress for risinglion.schwartzman.org
        if [ "$DEPLOYMENT_TYPE" == "production" ]; then
          echo "Deploying production ingress for risinglion.schwartzman.org..."
          envsubst < k8s/production-ingress.yaml | kubectl apply -n $NAMESPACE -f -

          # Also ensure the service exists in risinglion namespace for backward compatibility
          kubectl create namespace risinglion --dry-run=client -o yaml | kubectl apply -f -

          # Create an ExternalName service in risinglion namespace that points to the default namespace
          cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: rising-lion-game-service
  namespace: risinglion
spec:
  type: ExternalName
  externalName: rising-lion-game-service.default.svc.cluster.local
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
EOF

          # Create ingress in risinglion namespace pointing to the service
          cat <<EOF | kubectl apply -f -
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rising-lion-game-domain-ingress
  namespace: risinglion
  labels:
    app: rising-lion-game
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
spec:
  ingressClassName: nginx
  rules:
  - host: risinglion.schwartzman.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rising-lion-game-service
            port:
              number: 80
EOF
        fi
    
    - name: Wait for deployment
      run: |
        kubectl wait --for=condition=available --timeout=300s deployment/$APP_NAME -n $NAMESPACE
        echo "✅ Deployment is ready!"

    - name: Run health check
      run: |
        chmod +x scripts/healthcheck.sh
        ./scripts/healthcheck.sh
    
    - name: Get deployment info
      run: |
        echo "=== Deployment Information ==="
        echo "Namespace: $NAMESPACE"
        echo "App Name: $APP_NAME"
        echo "Image: $REGISTRY_NAME.azurecr.io/$APP_NAME:$IMAGE_TAG"
        echo ""
        echo "=== Service Status ==="
        kubectl get services -n $NAMESPACE
        echo ""
        echo "=== Pod Status ==="
        kubectl get pods -n $NAMESPACE
        echo ""
        echo "=== Ingress Status ==="
        kubectl get ingress -n $NAMESPACE
    
    - name: Install and fix nginx ingress controller
      run: |
        # Check if nginx ingress controller is installed
        if ! kubectl get namespace ingress-nginx > /dev/null 2>&1; then
          echo "Installing nginx ingress controller..."
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/cloud/deploy.yaml
        fi

        # Fix nginx controller node selectors to prevent scheduling issues
        echo "Fixing nginx controller node selectors..."
        kubectl patch deployment ingress-nginx-controller -n ingress-nginx --type=json -p='[{"op": "replace", "path": "/spec/template/spec/nodeSelector", "value": {"kubernetes.io/os": "linux"}}]' || true

        # Remove problematic webhook if it exists (it can cause deployment issues)
        kubectl delete validatingwebhookconfigurations ingress-nginx-admission --ignore-not-found=true

        # Wait for controller to be ready
        echo "Waiting for ingress controller to be ready..."
        kubectl wait --namespace ingress-nginx --for=condition=available deployment/ingress-nginx-controller --timeout=120s || true

        echo "✅ Nginx ingress controller is ready"
    
    - name: Deployment Summary
      run: |
        echo "## 🚀 Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "**Environment:** $DEPLOYMENT_TYPE" >> $GITHUB_STEP_SUMMARY
        echo "**Namespace:** $NAMESPACE" >> $GITHUB_STEP_SUMMARY
        echo "**Application:** $APP_NAME" >> $GITHUB_STEP_SUMMARY
        echo "**Image Tag:** $IMAGE_TAG" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "$DEPLOYMENT_TYPE" == "staging" ]; then
          echo "**🔗 Staging URL:** http://games.risinglion.dev/pr-${{ github.event.number }}" >> $GITHUB_STEP_SUMMARY
        else
          echo "**🔗 Production URL:** https://risinglion.schwartzman.org" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📊 Resource Status" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        kubectl get all -n $NAMESPACE >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY